import { Deal, DealType, DealStatus, User } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Suganya',
  role: 'Clerk',
  avatarUrl: 'https://ui-avatars.com/api/?name=Suganya+Argeen&background=0D8ABC&color=fff'
};

export const MOCK_DEALS: Deal[] = [
  // Active Deals
  {
    id: 'd1',
    fileNumber: '#26P-0059',
    client: { id: 'c1', firstName: 'John', lastName: 'Doe', email: 'john@example.com', phone: '555-0199' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of 71 Eagle Road',
    closingDate: '2026-02-05',
    openingDate: '2026-01-10',
    price: 0,
    progress: 45,
    tasks: [
      { 
        id: '416', 
        title: 'Upload Complete Agreement of Purchase and Sale and Amendments', 
        completed: true, 
        status: 'Completed', 
        dueDate: '2026-01-15', 
        completedAt: '2026-01-15 14:30',
        document: { name: 'APS_Signed.pdf', url: '#' }
      },
      { 
        id: '417', 
        title: 'Provide Personal Information', 
        completed: true, 
        status: 'Completed', 
        dueDate: '2026-01-16', 
        completedAt: '2026-01-16 09:15',
        document: { name: 'Client_Intake.pdf', url: '#' }
      },
      { id: '418', title: 'Upload Identification', completed: false, status: 'Pending', dueDate: '2026-02-01' },
      { id: '419', title: 'Status of Mortgage', completed: false, status: 'Pending', dueDate: '2026-02-02' },
      { id: '420', title: 'Upload Home Insurance Policy', completed: false, status: 'Pending', dueDate: '2026-02-03' },
      { id: '421', title: 'Schedule an Appointment', completed: false, status: 'Pending', dueDate: '2026-02-04' },
    ],
    milestones: [
      { id: '1178', title: 'Agreement of Purchase and Sale', status: 'Completed', milestoneDate: '2026-01-15', completedAt: '2026-01-15 10:30 AM', emailSent: true },
      { id: '1179', title: 'Initial Call', status: 'Completed', milestoneDate: '2026-01-16', completedAt: '2026-01-16 02:15 PM', emailSent: true },
      { id: '1180', title: 'Personal Information', status: 'In Progress', milestoneDate: '2026-01-18' },
      { id: '1181', title: 'Identification', status: 'Pending', milestoneDate: '2026-02-01' },
      { id: '1182', title: 'Title Search', status: '', milestoneDate: '2026-02-02' },
      { id: '1183', title: 'Financing Firm → Mortgage Instructions', status: '', milestoneDate: '2026-02-03' },
      { id: '1184', title: 'Aligned with Seller → Closing Date Coordination', status: '', milestoneDate: '2026-02-03' },
      { id: '1185', title: 'Financial Info Confirmed → Mortgage Details Confirmed', status: '', milestoneDate: '' },
      { id: '1186', title: 'Home Insurance', status: '', milestoneDate: '' },
      { id: '1187', title: 'Appointment Scheduled', status: '', milestoneDate: '' },
      { id: '1188', title: 'Documents Signed', status: '', milestoneDate: '' },
      { id: '1189', title: 'Funds received', status: '', milestoneDate: '' },
      { id: '1190', title: 'Transaction Completed', status: '', milestoneDate: '' },
      { id: '1191', title: 'Final Report Received', status: '', milestoneDate: '' },
    ],
    documents: [],
    notes: []
  },
  {
    id: 'd2',
    fileNumber: '#26S-0015',
    client: { id: 'c2', firstName: 'Jane', lastName: 'Smith', email: 'jane@example.com', phone: '555-0123' },
    type: DealType.SALE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Sale of 92 Conarty Crescent',
    closingDate: '2026-02-12',
    openingDate: '2026-01-05',
    requisitionDate: '2026-01-26',
    price: 850000,
    progress: 30,
    tasks: [],
    documents: [],
    notes: []
  },
  {
    id: 'd3',
    fileNumber: '#26P-0026',
    client: { id: 'c3', firstName: 'Alice', lastName: 'Wonder', email: 'alice@example.com', phone: '555-0999' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of 1206-1 Quarrington Lane, Toronto',
    closingDate: '2026-02-28',
    openingDate: '2026-01-09',
    price: 620000,
    progress: 15,
    tasks: [],
    documents: [],
    notes: []
  },
  // Recently Viewed
  {
    id: 'd4',
    fileNumber: '#26R-0062',
    client: { id: 'c4', firstName: 'Bob', lastName: 'Builder', email: 'bob@example.com', phone: '555-1111' },
    type: DealType.REFINANCE,
    status: DealStatus.PENDING,
    propertyAddress: 'Refinance of 55-57 Deacon Lane',
    closingDate: '2026-03-01',
    openingDate: '2026-01-27',
    price: 0,
    progress: 10,
    tasks: [],
    documents: [],
    notes: []
  },
  {
    id: 'd5',
    fileNumber: '#25P-0544',
    client: { id: 'c5', firstName: 'Charlie', lastName: 'Chaplin', email: 'charlie@example.com', phone: '555-2222' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of 1232-2545 Simcoe St N Oshawa',
    closingDate: '2026-02-15',
    openingDate: '2025-07-16',
    price: 550000,
    progress: 60,
    tasks: [],
    documents: [],
    notes: []
  },
  {
    id: 'd6',
    fileNumber: '#25S-0750',
    client: { id: 'c6', firstName: 'David', lastName: 'Beckham', email: 'david@example.com', phone: '555-3333' },
    type: DealType.SALE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Sale of 3 - 280 West Beaver Creek Rd, Richmond Hill',
    closingDate: '2026-02-20',
    openingDate: '2025-11-13',
    price: 1200000,
    progress: 75,
    tasks: [],
    documents: [],
    notes: []
  },
  // Upcoming Requisitions
  {
    id: 'd7',
    fileNumber: '#26P-0066',
    client: { id: 'c7', firstName: 'Eve', lastName: 'Polastri', email: 'eve@example.com', phone: '555-4444' },
    type: DealType.PURCHASE,
    status: DealStatus.URGENT,
    propertyAddress: 'Purchase of 507-80 Alton Towers Circle',
    closingDate: '2026-02-11',
    openingDate: '2026-01-20',
    requisitionDate: '2026-02-11',
    price: 600000,
    progress: 20,
    tasks: [{ id: 't1', title: 'Requisition Due', completed: false, dueDate: '2026-02-11', status: 'Pending' }],
    documents: [],
    notes: []
  },
  {
    id: 'd8',
    fileNumber: '#26P-0039',
    client: { id: 'c8', firstName: 'Frank', lastName: 'Castle', email: 'frank@example.com', phone: '555-5555' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of 221 The Meadows Avenue, Markham',
    closingDate: '2026-02-18',
    openingDate: '2026-01-15',
    requisitionDate: '2026-02-18',
    price: 900000,
    progress: 10,
    tasks: [{ id: 't2', title: 'Requisition Due', completed: false, dueDate: '2026-02-18', status: 'Pending' }],
    documents: [],
    notes: []
  },
  {
    id: 'd9',
    fileNumber: '#25P-0872',
    client: { id: 'c9', firstName: 'George', lastName: 'Costanza', email: 'george@example.com', phone: '555-6666' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of 36 Tudor Avenue, Ajax',
    closingDate: '2026-02-27',
    openingDate: '2025-12-05',
    requisitionDate: '2026-02-27',
    price: 750000,
    progress: 5,
    tasks: [{ id: 't3', title: 'Requisition Due', completed: false, dueDate: '2026-02-27', status: 'Pending' }],
    documents: [],
    notes: []
  },
  {
    id: 'd10',
    fileNumber: '#23P-0467',
    client: { id: 'c10', firstName: 'Harry', lastName: 'Potter', email: 'harry@example.com', phone: '555-7777' },
    type: DealType.PURCHASE,
    status: DealStatus.ACTIVE,
    propertyAddress: 'Purchase of Suite 4012 Unit 10, Level 35, Etobicoke, ON',
    closingDate: '2026-02-01',
    openingDate: '2023-05-24',
    price: 450000,
    progress: 90,
    tasks: [],
    documents: [],
    notes: []
  },
  {
    id: 'd11',
    fileNumber: '#24P-1155',
    client: { id: 'c11', firstName: 'Ian', lastName: 'Malcolm', email: 'ian@example.com', phone: '555-8888' },
    type: DealType.PURCHASE,
    status: DealStatus.CLOSED,
    propertyAddress: 'Purchase of 100 Hilborn Street, Plattsville, ON, N0J 1S0',
    closingDate: '2026-02-02',
    openingDate: '2024-11-27',
    price: 650000,
    progress: 100,
    tasks: [],
    documents: [],
    notes: []
  },
  {
    id: 'd12',
    fileNumber: '#25S-0853',
    client: { id: 'c12', firstName: 'Jack', lastName: 'Sparrow', email: 'jack@example.com', phone: '555-9999' },
    type: DealType.SALE,
    status: DealStatus.CLOSED,
    propertyAddress: 'Sale of 1401 Salem Road N, Ajax, ON, L1Z 0R9',
    closingDate: '2026-02-02',
    openingDate: '2025-11-13',
    requisitionDate: '2026-01-06',
    price: 880000,
    progress: 100,
    tasks: [],
    documents: [],
    notes: []
  }
];

export const NAV_ITEMS = [
  { label: 'Dashboard', id: 'dashboard', icon: 'LayoutDashboard' },
  { label: 'Search', id: 'search', icon: 'Search' },
  { label: 'Intake', id: 'intake', icon: 'ClipboardCheck' },
  { label: 'Tasks', id: 'tasks', icon: 'ListTodo' },
  { label: 'All Files', id: 'deals', icon: 'Files' },
  { 
    label: 'Templates', 
    id: 'templates', 
    icon: 'FileStack',
    children: [
      { label: 'Stage Templates', id: 'stage-templates' },
      { label: 'Task Templates', id: 'task-templates' },
      { label: 'Email Templates', id: 'email-templates' },
    ]
  },
  { label: 'Leads', id: 'leads', icon: 'Users' },
  { label: 'Settings', id: 'settings', icon: 'Settings' },
];
